# Generated by Django 5.1.3 on 2024-11-21 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cliente_id_alter_cliente_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
